config/routes.rb
Rails.application.routes.draw do
  resources :todoos

end

app/models/todoo.rb
class Todoo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todoos_controller.rb
class TodoosController < ApplicationController
  before_action :set_todoo, only: [:show, :edit, :update, :destroy]

  # GET /todoos
  # GET /todoos.json
  def index
    @todoos = Todoo.all
  end

  # GET /todoos/1
  # GET /todoos/1.json
  def show
  end

  # GET /todoos/new
  def new
    @todoo = Todoo.new
  end

  # GET /todoos/1/edit
  def edit
  end

  # POST /todoos
  # POST /todoos.json
  def create
    @todoo = Todoo.new(todoo_params)

    respond_to do |format|
      if @todoo.save
        format.html { redirect_to @todoo, notice: 'Todoo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todoo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todoos/1
  # PATCH/PUT /todoos/1.json
  def update
    respond_to do |format|
      if @todoo.update(todoo_params)
        format.html { redirect_to @todoo, notice: 'Todoo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoos/1
  # DELETE /todoos/1.json
  def destroy
    @todoo.destroy
    respond_to do |format|
      format.html { redirect_to todoos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoo
      @todoo = Todoo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoo_params
      params.require(:todoo).permit(:name, :finished)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todoos_helper.rb
module TodoosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todoos/_form.html.erb
<%= form_for(@todoo) do |f| %>
  <% if @todoo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todoo.errors.count, "error") %> prohibited this todoo from being saved:</h2>

      <ul>
      <% @todoo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :finished %><br>
    <%= f.check_box :finished %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todoos/edit.html.erb
<h1>Editing todoo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todoo %> |
<%= link_to 'Back', todoos_path %>

app/views/todoos/index.html.erb
<h1>Listing todoos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todoos.each do |todoo| %>
      <tr>
        <td><%= todoo.name %></td>
        <td><%= todoo.finished %></td>
        <td><%= link_to 'Show', todoo %></td>
        <td><%= link_to 'Edit', edit_todoo_path(todoo) %></td>
        <td><%= link_to 'Destroy', todoo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todoo', new_todoo_path %>

app/views/todoos/new.html.erb
<h1>New todoo</h1>

<%= render 'form' %>

<%= link_to 'Back', todoos_path %>

app/views/todoos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todoo.name %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @todoo.finished %>
</p>

<%= link_to 'Edit', edit_todoo_path(@todoo) %> |
<%= link_to 'Back', todoos_path %>